version: "3.3"

services:
  mesos-mini:
    image: minyk/mesos-mini:1.7-1.5.11
    privileged: true
    ports:
      - "5050:5050"
      - "5051:5051"
      - "8080:8080"
    links:
      - vault
    volumes:
      - ./build/libs:/plugins
      - ./plugin-conf-test.json:/plugin-conf-test.json
    environment:
      - MARATHON_DECLINE_OFFER_DURATION=3600000
      - MARATHON_MESOS_ROLE=public
      - MARATHON_PLUGIN_DIR=/plugins
      - MARATHON_PLUGIN_CONF=/plugin-conf-test.json
      - MARATHON_ENABLE_FEATURES=secrets,task_killing

  vault:
    image: vault:1.0.0
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=testroottoken
      - SKIP_SETCAP=true # suppressing Vault's IPC lock behavior which causes problems in Travis (see https://github.com/hashicorp/docker-vault/issues/24)
    ports:
      - "8200:8200"
